import hashlib
import random
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.database import ChatCache


def hash_prompt(prompt: str, model: str) -> str:
    """Generate SHA256 hash from prompt + model for cache lookup."""
    content = f"{prompt.strip().lower()}:{model}"
    return hashlib.sha256(content.encode()).hexdigest()


async def get_cached_response(
    prompt_hash: str, model: str, db: AsyncSession
) -> ChatCache | None:
    """Look up cached response by prompt hash and model."""
    stmt = select(ChatCache).where(
        ChatCache.prompt_hash == prompt_hash,
        ChatCache.model == model,
    )
    result = await db.execute(stmt)
    return result.scalar_one_or_none()


async def get_chat_by_id(chat_id: int, db: AsyncSession) -> ChatCache | None:
    """Retrieve a cached chat entry by its ID."""
    stmt = select(ChatCache).where(ChatCache.id == chat_id)
    result = await db.execute(stmt)
    return result.scalar_one_or_none()


async def save_to_cache(
    prompt: str,
    response: str,
    model: str,
    prompt_hash: str,
    db: AsyncSession,
) -> ChatCache:
    """Save AI response to database cache."""
    entry = ChatCache(
        prompt=prompt,
        response=response,
        model=model,
        prompt_hash=prompt_hash,
    )
    db.add(entry)
    await db.commit()
    await db.refresh(entry)
    return entry


async def call_ai_api(prompt: str, model: str, max_tokens: int) -> str:
    """
    Mock AI API call — simulates a response from an AI provider.

    In production, this would use httpx to call OpenAI/Groq API.
    For demo purposes, returns a simulated response.
    """
    # Simulated AI responses based on prompt content
    responses = [
        f"Based on my analysis of your prompt about '{prompt[:50]}...', "
        f"here is a comprehensive response generated by {model}. "
        "This is a mock response for demonstration purposes. "
        "In production, this would call the actual AI API endpoint.",

        f"[{model}] Great question! Regarding '{prompt[:40]}...': "
        "The answer involves several key concepts that are fundamental "
        "to understanding this topic. This simulated response demonstrates "
        "the gateway's proxy and caching capabilities.",

        f"AI Gateway Response ({model}): After processing your query "
        f"'{prompt[:35]}...', I can provide the following insights. "
        "Note: This is a mock response. The actual implementation would "
        "forward requests to the configured AI provider API.",
    ]
    return random.choice(responses)


async def check_database_health(db: AsyncSession) -> bool:
    """Check if database connection is healthy."""
    try:
        await db.execute(select(1))
        return True
    except Exception:
        return False
